---
- name: Copy jar to docker-host
  copy: src=app.jar  dest=/etc/mfp/app.jar

- name: Copy Dockerfile to docker-host
  copy: src=Dockerfile dest=/etc/mfp

- name: Stop and remove container
  command: docker rm -f mfp
  ignore_errors: yes

- name: Remove docker image
  command: docker rmi -f mfp
  ignore_errors: yes

- name: Create docker image
  command: docker build -f /etc/mfp/Dockerfile -t mfp /etc/mfp

- name: Start container
  command: docker run -p 8080:8080 --name mfp -d mfp
