---
- name: Copy jar to docker-host
  copy: src=management-of-fresh-products-1.0.0-SNAPSHOT.jar  dest=/home/mfp/mfp.jar

- name: Copy Dockerfile to docker-host
  copy: src=Dockerfile dest=/home/mfp

- name: Stop and remove container
  command: docker rm -f mfp
  ignore_errors: yes

- name: Remove docker image
  command: docker rmi -f mfp
  ignore_errors: yes

- name: Create docker image
  command: docker build -f /home/mfp/Dockerfile -t mfp /home/mfp

- name: Start container
  command: docker run -p 8080:8080 --name mfp -d mfp
