---
- name: Copy jar to docker-host
  copy: src=app.jar  dest=/etc/apps/{{ app_name }}.jar

- name: Copy Dockerfile to docker-host
  template: src=Dockerfile.j2 dest=/etc/apps/Dockerfile

- name: Stop and remove container
  command: docker rm -f {{ container_tag }}
  ignore_errors: yes

- name: Remove docker image
  command: docker rmi -f {{ docker_image_tag }}
  ignore_errors: yes

- name: Create docker image
  command: docker build -f /etc/apps/Dockerfile -t {{ docker_image_tag }}  /etc/apps/

- name: Start container
  command: docker run -p {{ app_port }}:{{ app_port }} --name {{ container_tag }} -d {{ docker_image_tag }}
